#if !canImport(ObjectiveC)
import XCTest

extension TokenParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TokenParserTests = [
        ("test_001", test_001),
        ("test_002", test_002),
        ("test_003", test_003),
        ("test_004", test_004),
        ("test_005", test_005),
        ("test_006", test_006),
        ("test_007", test_007),
        ("test_008", test_008),
        ("test_009", test_009),
        ("test_010", test_010),
        ("test_011", test_011),
        ("test_012", test_012),
        ("test_013", test_013),
        ("test_014", test_014),
        ("test_015", test_015),
        ("test_016", test_016),
        ("test_017", test_017),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TokenParserTests.__allTests__TokenParserTests),
    ]
}
#endif
