#if !canImport(ObjectiveC)
import XCTest

extension RollbackTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RollbackTests = [
        ("test_001", test_001),
        ("test_002", test_002),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RollbackTests.__allTests__RollbackTests),
    ]
}
#endif
