#if !canImport(ObjectiveC)
import XCTest

extension CommentLineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommentLineTests = [
        ("test_001", test_001),
        ("test_002", test_002),
        ("test_003", test_003),
        ("test_004", test_004),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CommentLineTests.__allTests__CommentLineTests),
    ]
}
#endif
