#if !canImport(ObjectiveC)
import XCTest

extension LocalizedStringsFileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LocalizedStringsFileTests = [
        ("test_001", test_001),
        ("test_002", test_002),
        ("test_003", test_003),
        ("test_004", test_004),
        ("test_005", test_005),
        ("test_006", test_006),
        ("test_007", test_007),
    ]
}

extension LogicalParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LogicalParserTests = [
        ("test_001", test_001),
        ("test_002", test_002),
        ("test_003", test_003),
        ("test_004", test_004),
        ("test_005", test_005),
        ("test_006", test_006),
        ("test_007", test_007),
        ("test_008", test_008),
        ("test_009", test_009),
        ("test_010", test_010),
        ("test_011", test_011),
        ("test_012", test_012),
        ("test_013", test_013),
        ("test_014", test_014),
        ("test_015", test_015),
        ("test_016", test_016),
        ("test_017", test_017),
        ("test_018", test_018),
        ("test_019", test_019),
        ("test_020", test_020),
        ("test_021", test_021),
        ("test_022", test_022),
        ("test_023", test_023),
        ("test_024", test_024),
        ("test_025", test_025),
    ]
}

extension StringsFileParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringsFileParserTests = [
        ("test_001", test_001),
        ("test_002", test_002),
        ("test_003", test_003),
        ("test_004", test_004),
        ("test_005", test_005),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LocalizedStringsFileTests.__allTests__LocalizedStringsFileTests),
        testCase(LogicalParserTests.__allTests__LogicalParserTests),
        testCase(StringsFileParserTests.__allTests__StringsFileParserTests),
    ]
}
#endif
